{{- $fullName := include "jachai-map.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jachai-map.fullname" . }}
  labels:
    {{- include "jachai-map.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "jachai-map.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jachai-map.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/git-sha: {{ .Values.image.tag | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jachai-map.serviceAccountName" . }}
{{- if .Values.configMap.enabled }}
      volumes:
      - name:  {{ $fullName }}
        configMap:
          name:  {{ $fullName }}
          defaultMode: 420
{{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.configMap.enabled }}
          volumeMounts:
          {{- range $item := .Values.configMap.volumeMounts }}
          - name: {{ $fullName }}
          {{- toYaml $item | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if or .Values.environment .Values.environmentSecrets }}
          envFrom:
          {{- end }}
          {{- if .Values.environment }}
          - configMapRef:
              name: "{{ include "jachai-map.fullname" . }}-env"
          {{- end }}
          {{- if .Values.environmentSecrets }}
          - secretRef:
              name: "{{ include "jachai-map.fullname" . }}-env"
          {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
