{{- if .Values.environmentSecrets }}
{{- $fullName := include "jachai-map.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jachai-map.fullname" . }}-env
  labels:
    {{- include "jachai-map.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.environmentSecrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
