environmentSecrets:
    JWT_KEY: ENC[AES256_GCM,data:u9yydLVLzuCcH7dzA+D1503yrTHSeCt8blMO3iND5YJQV1Vbwff3TvRXQZlAhVV8clrVU1c7THqybeCOovE+mQ==,iv:TKJ/zefsBBkkBurhnX/gk6YR48G+al8VuLoVN0GgeRY=,tag:lxCSONC8njLQaco10F0MCg==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:ttUC7wP/F25ffUMQa9TxM4+o8OiIER0HphYQWZKR3ur2UhDMWjBTE2fUp4XGcPy5ibafeNMVH3aW2GDljImoW3CmqFL40f/rXz4TxTtoirYrqOzBODbfb7C3uhrcXAM3l7N+zk2+9wGdl7i+noMAJ4VsBOU+6bgC4MNJ0WXXcNOIdNsKAt2APJc1kygkGVLZJoxLjT2X64tlhFN2dAo=,iv:emO3ClYWpk772zXKZNXtHpfb/ogimfWEAtOG4Upsvtg=,tag:Mh25J6VnYh6KAK1X6IWJ7A==,type:str]
    BARI_KOI_API_KEY: ENC[AES256_GCM,data:nuZ7x2wGobXUqFevuQOUXa8vkxk=,iv:fha5zIawvobNG81aj3MbuwF912Zq+9Wo8X9ZhUGc/yE=,tag:2ejOZF5NoqUN96HsZ6Jlaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-28T04:04:19Z"
    mac: ENC[AES256_GCM,data:D4IMFwnBG/f77HQ/9575miMzEImzsAbpKAXbTiQNXZrHp1z35IjunvHufVnFZj+adAgNu/syCTCOA+3eloacKMdG2mAg/tOpkDIm/sQnRJRas5PyMx54ZsLyehxm5+v0kBZZEY+KvWnEnRCDTtJMnM1foc2/9Ltwr5iIgLZRbeg=,iv:nZyJwiAmmJ6F8AiZE/zUUkQb0gMLdsaLTs8PgKJwm7k=,tag:LXsFOw0xjx9AEKQNSuM+aw==,type:str]
    pgp:
        - created_at: "2021-09-11T03:10:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAy0b0ETWEWXrAQv+KCm5/5QZMImcosl2768zNo23OcewH1oYcmYI13shuIoX
            EdT3LLnkZwABglyXu6utXaYEG7YQNvK25BhSt8UfKUeuWzLm11OHQkGOc3+K5L7g
            rffYhRjtzIlWqdFGyCNY7QopqT0EONp6sWGjRzux4yS65yZvol+MdMQfzXH48EO4
            IqPOEf11sugCniWzz5ycKFChxsqYSPrl4nARh2WQ90wENIUEp0qKiOvLb2juDT26
            QJl5qU3RV3bKUphDtCILtI9MpXDom2NmWVM8wBFgk6kkFpIiRGLLz7w+7v/euQxB
            ufYp54pIx0wz64SnnVPx7hk6lPYDgFzwZoNYAeXsIhxNvRwdW2hsFg7ym8E2LdhJ
            eO7SW/OdlWe1MmbUz5b8irkCh59gy8oiZ9XNGKAC8b1PzeUstpUFxtYbgtYOQn7D
            uncLGh7eBKJzLh/d4p+H+Z6IZEMMGWePfyFtFtVSVL+yWgIXiOR+yVWEPicow4DV
            4dtVPTXJE0caOzUbQZOv0lwBRen2ZceQw2lXJt9PmQe9UbffadV+eGLURFxfP6dQ
            PhNo+pd6IqWmKt6q68+p22LqJ+ZATbZBMg3KttMp7PQEWpT/h26bMMg0zGnr0F0q
            8vG0xysX6QD/mLGXJA==
            =60o/
            -----END PGP MESSAGE-----
          fp: 69765D6B78F867C7E5820EF482716F368FA66956
    unencrypted_suffix: _unencrypted
    version: 3.7.1
